In [2]:
import numpy as np

In [78]:
#Entrada dos dados
a = np.array([[1,3,1],[1,1,2],[2,2,0]])
b = np.array([[20],[10],[11]])

In [44]:
# Cálculo da determinante
det = np.linalg.det(a)
round(det,2)

12.0

In [118]:
#Criando a matrix U
u = np.hstack((a,b))
print(u)

ordem, colunas = u.shape # Ordem da matrix
print(ordem, colunas)

[[ 1  3  1 20]
 [ 1  1  2 10]
 [ 2  2  0 11]]
3 4


In [96]:
print(u[0,:])
print(u[1,:])

u[1,:] = u[1,:]-1/2*u[0,:]

print(u)

[-2  0  1  3]
[[ 2  2  0 11]
 [ 0  0  2  4]]
[[-2  0  1  3]
 [ 3  2  0  9]
 [ 0  0  2  4]]


### Função escalonamento

| Input | Output |
|-------|--------|
| Matrix u | Matrix escalonada |
| | Nº de trocas |

In [119]:
n_trocas = 0

#Considera que a matrix é quadrada, verificar se é possível matrix não quadrada
for j in range(colunas-1): #Itera entre as colunas menos a final
    #print(f"coluna {j}: {u[j:,j]}")
    id_pivo = np.argmax(u[j:,j])+j
    #print(f"id_pivo coluna {j}: {id_pivo}")
    if id_pivo == j:
        pivo = u[j,id_pivo]
        #print(f"Pivo correto: {pivo}")
        #print(u)


    else:
        #print(f"Trocando linhas {j} e {id_pivo} ")
        #print('U antigo')
        #print(u)
        u[[j,id_pivo]] = u[[id_pivo,j]]
        #print('u novo')
        #print(u)
        n_trocas += 1
        #print(f" Troca nº: {n_trocas}")
        pivo = u[j,j]
        #print(f"Pivo: {pivo}")
    for i in range(j+1,ordem): #Não itera a 1º linha
        m = u[i,j]/pivo
        #print(f"m = {u[i,j]}/{pivo} = {m}")
        u[i,:] = u[i,:] - m*u[j,:]
        #print(f"L{i+1} = L{i+1} - {m}*L{j+1}")
        #print(u)
    
    #print("-----------------------------------------")

print(f"Nº trocas: {n_trocas}")
print(u)


Nº trocas: 2
[[ 2  2  0 11]
 [ 0  2  1 14]
 [ 0  0  2  4]]


### Resolução sistema

Recebe a matrix escalonada e retorna o resultado do sistema

In [19]:
range(3)

range(0, 3)