In [41]:
import numpy as np

In [43]:
#Entrada dos dados
ma = np.array([[8,1,1],[1,5,1],[2,1,2]],dtype=float)
mb = np.array([[20],[10],[11]],dtype=float)

In [44]:
# Cálculo da determinante
det = np.linalg.det(ma)
round(det,2)

63.0

In [45]:
#Criando a matrix U
u = np.hstack((ma,mb))
print(u)

[[ 8.  1.  1. 20.]
 [ 1.  5.  1. 10.]
 [ 2.  1.  2. 11.]]


### Função escalonamento

| Input | Output |
|-------|--------|
| Matrix u | Matrix escalonada |
| | Nº de trocas |
| | Ordem |

In [46]:
n_trocas = 0
ordem, colunas = u.shape # Ordem da matrix

#Considera que a matrix é quadrada, verificar se é possível matrix não quadrada
for j in range(colunas-1): #Itera entre as colunas menos a final
    print(f"coluna {j}: {u[j:,j]}")
    id_pivo = np.argmax(u[j:,j])+j
    print(f"id_pivo coluna {j}: {id_pivo}")
    if id_pivo == j:
        pivo = u[j,id_pivo]
        print(f"Pivo correto: {pivo}")
        print(u)


    else:
        print(f"Trocando linhas {j} e {id_pivo} ")
        print('U antigo')
        print(u)
        u[[j,id_pivo]] = u[[id_pivo,j]]
        print('u novo')
        print(u)
        n_trocas += 1
        print(f" Troca nº: {n_trocas}")
        pivo = u[j,j]
        print(f"Pivo: {pivo}")
    for i in range(j+1,ordem): #Não itera a 1º linha
        m = u[i,j]/pivo
        print(f"m = {u[i,j]}/{pivo} = {m}")
        u[i,:] = u[i,:] - m*u[j,:]
        print(f"L{i+1} = L{i+1} - {m}*L{j+1}")
        print(u)
    
    print("-----------------------------------------")

print(f"Ordem: {ordem}")
print(f"Nº trocas: {n_trocas}")
print(u)


coluna 0: [8. 1. 2.]
id_pivo coluna 0: 0
Pivo correto: 8.0
[[ 8.  1.  1. 20.]
 [ 1.  5.  1. 10.]
 [ 2.  1.  2. 11.]]
m = 1.0/8.0 = 0.125
L2 = L2 - 0.125*L1
[[ 8.     1.     1.    20.   ]
 [ 0.     4.875  0.875  7.5  ]
 [ 2.     1.     2.    11.   ]]
m = 2.0/8.0 = 0.25
L3 = L3 - 0.25*L1
[[ 8.     1.     1.    20.   ]
 [ 0.     4.875  0.875  7.5  ]
 [ 0.     0.75   1.75   6.   ]]
-----------------------------------------
coluna 1: [4.875 0.75 ]
id_pivo coluna 1: 1
Pivo correto: 4.875
[[ 8.     1.     1.    20.   ]
 [ 0.     4.875  0.875  7.5  ]
 [ 0.     0.75   1.75   6.   ]]
m = 0.75/4.875 = 0.15384615384615385
L3 = L3 - 0.15384615384615385*L2
[[ 8.          1.          1.         20.        ]
 [ 0.          4.875       0.875       7.5       ]
 [ 0.          0.          1.61538462  4.84615385]]
-----------------------------------------
coluna 2: [1.61538462]
id_pivo coluna 2: 2
Pivo correto: 1.6153846153846154
[[ 8.          1.          1.         20.        ]
 [ 0.          4.875      

### Resolução sistema

Recebe a matrix escalonada e retorna o resultado do sistema

In [36]:
# Backup de u para prototipagem
u_bkp = np.copy(u)

In [37]:
# Restaura u para o valor original do backup
u = np.copy(u_bkp)
print(u)

[[ 2.   2.   0.  11. ]
 [ 0.   2.   1.   4.5]
 [ 0.   0.   2.  14.5]]


In [47]:
# Resolução do sistema
res = []

for n,i in enumerate(u[::-1]):
    print(f"X{len(u)-n}")
    print()
    print(f"linha: {i}")
    print(f"valor igualdade: {round(i[-1],3)}")
    print(f"coeficientes: {i[-(n+1):-1]}")

    subtracao = 0
    for k,a in enumerate(i[-(n+1):-1]):
        print(f"c inicial: {subtracao}")
        print(f"res: {res}")
        print(f"calculo: {a} * {res[k-1]}")
        subtracao += a*res[k-1]
        print(f"c final: {subtracao}")
        print()

    x = (i[-1]-subtracao)/i[-(n+2)]
    print()
    print(f"X{len(u)-n} = {round(i[-1],3)} - {round(subtracao,3)} / {round(i[-(n+2)],3)}")
    subtracao = 0
    res.append(round(x,3))
    print(f"X{len(u)-n} = {round(x,3)}")
    print("----------------------------")
    print()

res = res[::-1]
print(f"Resolução: {res}")

X3

linha: [0.         0.         1.61538462 4.84615385]
valor igualdade: 4.846
coeficientes: []

X3 = 4.846 - 0 / 1.615
X3 = 3.0
----------------------------

X2

linha: [0.    4.875 0.875 7.5  ]
valor igualdade: 7.5
coeficientes: [0.875]
c inicial: 0
res: [3.0]
calculo: 0.875 * 3.0
c final: 2.625


X2 = 7.5 - 2.625 / 4.875
X2 = 1.0
----------------------------

X1

linha: [ 8.  1.  1. 20.]
valor igualdade: 20.0
coeficientes: [1. 1.]
c inicial: 0
res: [3.0, 1.0]
calculo: 1.0 * 1.0
c final: 1.0

c inicial: 1.0
res: [3.0, 1.0]
calculo: 1.0 * 3.0
c final: 4.0


X1 = 20.0 - 4.0 / 8.0
X1 = 2.0
----------------------------

Resolução: [2.0, 1.0, 3.0]
