In [2]:
import numpy as np

In [176]:
#Entrada dos dados
ma = np.array([[1,5,1],[8,1,1],[2,1,2]],dtype=float)
mb = np.array([[10],[20],[11]],dtype=float)

In [159]:
# Cálculo da determinante
det = np.linalg.det(a)
round(det,2)

8.0

In [177]:
#Criando a matrix U
u = np.hstack((ma,mb))
print(u)

[[ 1.  5.  1. 10.]
 [ 8.  1.  1. 20.]
 [ 2.  1.  2. 11.]]


### Função escalonamento

| Input | Output |
|-------|--------|
| Matrix u | Matrix escalonada |
| | Nº de trocas |
| | Ordem |

In [178]:
n_trocas = 0
ordem, colunas = u.shape # Ordem da matrix

#Considera que a matrix é quadrada, verificar se é possível matrix não quadrada
for j in range(colunas-1): #Itera entre as colunas menos a final
    #print(f"coluna {j}: {u[j:,j]}")
    id_pivo = np.argmax(u[j:,j])+j
    #print(f"id_pivo coluna {j}: {id_pivo}")
    if id_pivo == j:
        pivo = u[j,id_pivo]
        #print(f"Pivo correto: {pivo}")
        #print(u)


    else:
        #print(f"Trocando linhas {j} e {id_pivo} ")
        #print('U antigo')
        #print(u)
        u[[j,id_pivo]] = u[[id_pivo,j]]
        #print('u novo')
        #print(u)
        n_trocas += 1
        #print(f" Troca nº: {n_trocas}")
        pivo = u[j,j]
        #print(f"Pivo: {pivo}")
    for i in range(j+1,ordem): #Não itera a 1º linha
        m = u[i,j]/pivo
        #print(f"m = {u[i,j]}/{pivo} = {m}")
        u[i,:] = u[i,:] - m*u[j,:]
        #print(f"L{i+1} = L{i+1} - {m}*L{j+1}")
        #print(u)
    
    #print("-----------------------------------------")

print(f"Ordem: {ordem}")
print(f"Nº trocas: {n_trocas}")
print(u)


coluna 0: [1. 8. 2.]
id_pivo coluna 0: 1
Trocando linhas 0 e 1 
U antigo
[[ 1.  5.  1. 10.]
 [ 8.  1.  1. 20.]
 [ 2.  1.  2. 11.]]
u novo
[[ 8.  1.  1. 20.]
 [ 1.  5.  1. 10.]
 [ 2.  1.  2. 11.]]
 Troca nº: 1
Pivo: 8.0
m = 1.0/8.0 = 0.125
L2 = L2 - 0.125*L1
[[ 8.     1.     1.    20.   ]
 [ 0.     4.875  0.875  7.5  ]
 [ 2.     1.     2.    11.   ]]
m = 2.0/8.0 = 0.25
L3 = L3 - 0.25*L1
[[ 8.     1.     1.    20.   ]
 [ 0.     4.875  0.875  7.5  ]
 [ 0.     0.75   1.75   6.   ]]
-----------------------------------------
coluna 1: [4.875 0.75 ]
id_pivo coluna 1: 1
Pivo correto: 4.875
[[ 8.     1.     1.    20.   ]
 [ 0.     4.875  0.875  7.5  ]
 [ 0.     0.75   1.75   6.   ]]
m = 0.75/4.875 = 0.15384615384615385
L3 = L3 - 0.15384615384615385*L2
[[ 8.          1.          1.         20.        ]
 [ 0.          4.875       0.875       7.5       ]
 [ 0.          0.          1.61538462  4.84615385]]
-----------------------------------------
coluna 2: [1.61538462]
id_pivo coluna 2: 2
Pivo cor

[[ 8.          1.          1.         20.        ]
 [ 0.          4.875       0.875       7.5       ]
 [ 0.          0.          1.61538462  4.84615385]]

### Resolução sistema

Recebe a matrix escalonada e retorna o resultado do sistema

In [120]:
# Backup de u para prototipagem
u_bkp = np.copy(u)

In [121]:
# Restaura u para o valor original do backup
u = np.copy(u_bkp)
print(u)

[[ 2  2  0 11]
 [ 0  2  1 14]
 [ 0  0  2  4]]


In [175]:
# Resolução do sistema
res = []

for n,i in enumerate(u[::-1]):
    print(f"n: {n}")
    print(f"i: {i}")
    print(f"valor final: {i[-1]}")
    print(f"cof já calculados: {i[-(n+1):-1]}")
    c = 0
    for a in i[-(n+1):-1]:
        print(f"calculados: {res[n-1]}")
        c += a*res[n-1]
        print(f"subtração: {c}")
    b = i[-1]-c
    x = b/i[-(n+2)]
    res.append(x)
    print(f"x: {x}")
    print()

print(f"Resolução: {res}")

n: 0
i: [0.         0.         1.61538462 4.84615385]
valor final: 4.846153846153846
cof já calculados: []
x: 2.9999999999999996

n: 1
i: [0.    4.875 0.875 7.5  ]
valor final: 7.5
cof já calculados: [0.875]
calculados: 2.9999999999999996
subtração: 2.6249999999999996
x: 1.0

n: 2
i: [ 8.  1.  1. 20.]
valor final: 20.0
cof já calculados: [1. 1.]
calculados: 1.0
subtração: 1.0
calculados: 1.0
subtração: 2.0
x: 2.25

Resolução: [2.9999999999999996, 1.0, 2.25]


In [134]:
res = np.array([])
print(res[0])

IndexError: index 0 is out of bounds for axis 0 with size 0